hand_leds:
  - id: 16
    position: [0.0, -0.09, -0.0150]
  - id: 17
    position: [0.0, -0.06, 0.045]
  - id: 18
    position: [-0.03, -0.06, 0.0]
  - id: 19
    position: [0.0, -0.06, -0.015]
  - id: 20
    position: [0.03, -0.06, 0.015]