leds:
  - id: 45
    position: [-0.0300, 0.0, 0.0]
  - id: 44
    position: [0.0, -0.030, 0.0]
  - id: 42
    position: [0.0, 0.030, 0.0]
  - id: 40
    position: [0.030, 0.0, 0.0]
  - id: 47
    position: [0.0, 0.0, -0.015]